### ISSUE TITLE
Show extra version info

### ISSUE THREAD

**Issue by tjorim** [custom-components/sensor.versions#3]
**Is your feature request related to a problem? Please describe.**
Not really, it's more a nice to have. The json version file offers more than only HA version as shown below:
```json
{
  "channel": "beta",
  "supervisor": "128",
  "homeassistant": {
    "default": "0.77.1",
    "qemux86": "0.77.1",
    "qemux86-64": "0.77.1",
    "qemuarm": "0.77.1",
    "qemuarm-64": "0.77.1",
    "intel-nuc": "0.77.1",
    "raspberrypi": "0.77.1",
    "raspberrypi2": "0.77.1",
    "raspberrypi3": "0.77.1",
    "raspberrypi3-64": "0.77.1",
    "tinker": "0.77.1",
    "odroid-c2": "0.77.1",
    "odroid-xu": "0.77.1"
  },
  "hassos": {
    "ova": "1.10",
    "rpi": "1.10",
    "rpi0-w": "1.10",
    "rpi2": "1.10",
    "rpi3": "1.10",
    "rpi3-64": "1.10",
    "tinker": "2.2",
    "odroid-c2": "2.2"
  },
  "hassos-cli": "6"
}
```
Let users choose to show these, like both the latest homeassistant and HassOS versions for a raspi2.

**Describe the solution you'd like**
Based on the install method and options specified in the configuration, show the version for supervisor and hassos as well. Since there is still a difference between hassio installs (resinOS or hassOS) an extra 'installation'-option might be needed. Supervisor is used on both, host os version only on hassOS.

**Additional context**
An update to the pyhaversion might be needed.

**Comment by ludeeus** [comment]
Partly solved in https://github.com/custom-components/sensor.versions/releases/tag/0.2.0
Could use some filter logic to automatically choose the board.
hassio API maybe

**Comment by ludeeus** [comment]
This is now taken care of in 0.3.0
