### ISSUE TITLE
🔥 Deprecation warning.

### ISSUE THREAD

**Issue by ludeeus** [custom-components/sensor.versions#6]
This platform is merged in Home Assistant and when released this repo will be archived and deprecated.

**Comment by bosbefok** [comment]
Please tell me which version it was merged into and the name of the component/sensor.

**Comment by ludeeus** [comment]
It is not released yet, but it is part of the sensor.version

**Comment by ludeeus** [comment]
This sensor platform is now released in Home Assistant 0.82.0 as part of the `sensor.version` platform.
<https://www.home-assistant.io/components/sensor.version/>
